export const CONCEPTS = [
  {
    id: "indexing",
    title: "DB Indexing",
    hook: "Your query takes 4 seconds. Why?",
    icon: "📇",
    category: "databases",
    status: "live",
    path: "concepts/db-indexing/",
  },
  {
    id: "query-optimization",
    title: "Query Optimization",
    hook: "Same result. 50x slower. Spot the difference.",
    icon: "🔍",
    category: "databases",
    status: "live",
    path: "concepts/query-optimization/",
  },
  {
    id: "normalization",
    title: "Normalization",
    hook: "Your data is duplicated 14 times. On purpose?",
    icon: "🗃️",
    category: "databases",
    status: "locked",
    path: null,
  },
  {
    id: "transactions",
    title: "Transactions",
    hook: "Half the payment went through. Half didn't.",
    icon: "💳",
    category: "databases",
    status: "locked",
    path: null,
  },

  {
    id: "deadlock",
    title: "Deadlocks",
    hook: "Everything just... stopped.",
    icon: "💀",
    category: "concurrency",
    status: "locked",
    path: null,
  },
  {
    id: "race",
    title: "Race Conditions",
    hook: "Run it twice. Different answer.",
    icon: "🏎️",
    category: "concurrency",
    status: "locked",
    path: null,
  },
  {
    id: "mutex",
    title: "Mutexes",
    hook: "Only one thread gets in. The rest wait.",
    icon: "🚪",
    category: "concurrency",
    status: "locked",
    path: null,
  },
  {
    id: "semaphore",
    title: "Semaphores",
    hook: "Three can enter. The fourth watches.",
    icon: "🚦",
    category: "concurrency",
    status: "locked",
    path: null,
  },

  {
    id: "auth",
    title: "Auth Holes",
    hook: "Skip login. See what happens.",
    icon: "🛡️",
    category: "security",
    status: "locked",
    path: null,
  },
  {
    id: "sql-injection",
    title: "SQL Injection",
    hook: "Type something creative in the search bar.",
    icon: "💉",
    category: "security",
    status: "locked",
    path: null,
  },
  {
    id: "xss",
    title: "XSS Attacks",
    hook: "Your comment just ran JavaScript.",
    icon: "🕷️",
    category: "security",
    status: "locked",
    path: null,
  },
  {
    id: "csrf",
    title: "CSRF",
    hook: "You clicked a link. It transferred your money.",
    icon: "🔗",
    category: "security",
    status: "locked",
    path: null,
  },
  {
    id: "hashing",
    title: "Hashing vs Encryption",
    hook: "One is a one-way door. Guess which.",
    icon: "🔐",
    category: "security",
    status: "locked",
    path: null,
  },

  {
    id: "testing",
    title: "Tests",
    hook: '"Works on my machine." Famous last words.',
    icon: "🧪",
    category: "reliability",
    status: "locked",
    path: null,
  },
  {
    id: "error-handling",
    title: "Error Handling",
    hook: "Catch nothing. See everything burn.",
    icon: "🔥",
    category: "reliability",
    status: "locked",
    path: null,
  },
  {
    id: "logging",
    title: "Logging",
    hook: "Something crashed. No logs. Good luck.",
    icon: "📝",
    category: "reliability",
    status: "locked",
    path: null,
  },
  {
    id: "retry-logic",
    title: "Retry Logic",
    hook: "It failed. So you tried again. 10,000 times.",
    icon: "🔄",
    category: "reliability",
    status: "locked",
    path: null,
  },

  {
    id: "caching",
    title: "Caching",
    hook: "First load: 3 seconds. Second: instant. Why?",
    icon: "⚡",
    category: "performance",
    status: "locked",
    path: null,
  },
  {
    id: "lazy-loading",
    title: "Lazy Loading",
    hook: "Load everything now, or only what you need?",
    icon: "🦥",
    category: "performance",
    status: "locked",
    path: null,
  },
  {
    id: "pagination",
    title: "Pagination",
    hook: "You just loaded 1 million rows. Congrats.",
    icon: "📄",
    category: "performance",
    status: "locked",
    path: null,
  },
  {
    id: "connection-pooling",
    title: "Connection Pooling",
    hook: "1000 users. 5 connections. Do the math.",
    icon: "🏊",
    category: "performance",
    status: "locked",
    path: null,
  },

  {
    id: "dns",
    title: "DNS",
    hook: "You typed a name. The internet found a number.",
    icon: "🌐",
    category: "networking",
    status: "locked",
    path: null,
  },
  {
    id: "tcp-vs-udp",
    title: "TCP vs UDP",
    hook: "One guarantees delivery. One doesn't care.",
    icon: "📡",
    category: "networking",
    status: "locked",
    path: null,
  },
  {
    id: "latency",
    title: "Latency",
    hook: "200ms. You felt that, right?",
    icon: "⏱️",
    category: "networking",
    status: "locked",
    path: null,
  },
  {
    id: "load-balancing",
    title: "Load Balancing",
    hook: "One server is drowning. Three are idle.",
    icon: "⚖️",
    category: "networking",
    status: "locked",
    path: null,
  },

  {
    id: "memory-leak",
    title: "Memory Leaks",
    hook: "RAM usage: 98%. You allocated. Never freed.",
    icon: "🧠",
    category: "os",
    status: "locked",
    path: null,
  },
  {
    id: "process-vs-thread",
    title: "Process vs Thread",
    hook: "Same house, different rooms. Or different houses entirely.",
    icon: "🧵",
    category: "os",
    status: "locked",
    path: null,
  },
  {
    id: "scheduling",
    title: "CPU Scheduling",
    hook: "5 tasks. 1 CPU. Who goes first?",
    icon: "📋",
    category: "os",
    status: "locked",
    path: null,
  },
  {
    id: "virtual-memory",
    title: "Virtual Memory",
    hook: "Your app thinks it has 16GB. It has 4.",
    icon: "💾",
    category: "os",
    status: "locked",
    path: null,
  },

  {
    id: "hash-tables",
    title: "Hash Tables",
    hook: "O(1) lookup. Until it isn't.",
    icon: "🗄️",
    category: "data-structures",
    status: "locked",
    path: null,
  },
  {
    id: "trees",
    title: "Trees",
    hook: "Sorted insertion. Balanced search. One bad rotation.",
    icon: "🌳",
    category: "data-structures",
    status: "locked",
    path: null,
  },
  {
    id: "graphs",
    title: "Graphs",
    hook: "Shortest path. Unless there's a cycle.",
    icon: "🕸️",
    category: "data-structures",
    status: "locked",
    path: null,
  },
  {
    id: "stacks-queues",
    title: "Stacks & Queues",
    hook: "First in, first out. Or last in, first out. Pick one.",
    icon: "📚",
    category: "data-structures",
    status: "locked",
    path: null,
  },

  {
    id: "api-design",
    title: "API Design",
    hook: "Your endpoint returns 47 fields. The client needs 2.",
    icon: "🔌",
    category: "architecture",
    status: "locked",
    path: null,
  },
  {
    id: "microservices",
    title: "Microservices",
    hook: "You split the monolith. Now you have 50 problems.",
    icon: "🧩",
    category: "architecture",
    status: "locked",
    path: null,
  },
  {
    id: "rate-limiting",
    title: "Rate Limiting",
    hook: "1000 requests per second. From one user.",
    icon: "🚧",
    category: "architecture",
    status: "locked",
    path: null,
  },
  {
    id: "message-queues",
    title: "Message Queues",
    hook: "Fire and forget. Except when you shouldn't forget.",
    icon: "📬",
    category: "architecture",
    status: "locked",
    path: null,
  },
  {
    id: "event-driven",
    title: "Event-Driven Architecture",
    hook: "Something happened. 12 services reacted.",
    icon: "⚡",
    category: "architecture",
    status: "locked",
    path: null,
  },

  {
    id: "ci-cd",
    title: "CI/CD",
    hook: "Push to main. Pray it deploys.",
    icon: "🚀",
    category: "devops",
    status: "locked",
    path: null,
  },
  {
    id: "containers",
    title: "Containers",
    hook: "Works on my machine. So we ship your machine.",
    icon: "📦",
    category: "devops",
    status: "locked",
    path: null,
  },
  {
    id: "monitoring",
    title: "Monitoring",
    hook: "Your app crashed 3 hours ago. Nobody noticed.",
    icon: "📊",
    category: "devops",
    status: "locked",
    path: null,
  },

  {
    id: "sorting",
    title: "Sorting",
    hook: "Bubble sort on a million items. Go get coffee.",
    icon: "🔢",
    category: "algorithms",
    status: "locked",
    path: null,
  },
  {
    id: "big-o",
    title: "Big O",
    hook: "O(n²). Sounds fine. Until n = 100,000.",
    icon: "📈",
    category: "algorithms",
    status: "locked",
    path: null,
  },
  {
    id: "recursion",
    title: "Recursion",
    hook: "It calls itself. Then itself. Then itself. Then—",
    icon: "🪞",
    category: "algorithms",
    status: "locked",
    path: null,
  },
  {
    id: "dynamic-programming",
    title: "Dynamic Programming",
    hook: "You solved the same subproblem 47 times.",
    icon: "🧮",
    category: "algorithms",
    status: "locked",
    path: null,
  },
];

export const CATEGORIES = {
  databases: { label: "Databases", icon: "🗃️", order: 1 },
  concurrency: { label: "Concurrency", icon: "⚙️", order: 2 },
  security: { label: "Security", icon: "🔒", order: 3 },
  reliability: { label: "Reliability", icon: "🛠️", order: 4 },
  performance: { label: "Performance", icon: "⚡", order: 5 },
  networking: { label: "Networking", icon: "🌐", order: 6 },
  os: { label: "OS & Systems", icon: "💻", order: 7 },
  "data-structures": { label: "Data Structures", icon: "📦", order: 8 },
  architecture: { label: "Architecture", icon: "🏗️", order: 9 },
  devops: { label: "DevOps", icon: "🚀", order: 10 },
  algorithms: { label: "Algorithms", icon: "🧮", order: 11 },
};

export function getConceptsByCategory(categoryId) {
  return CONCEPTS.filter((c) => c.category === categoryId);
}

export function getCategoriesInOrder() {
  return Object.entries(CATEGORIES)
    .sort(([, a], [, b]) => a.order - b.order)
    .map(([id, meta]) => ({ id, ...meta }));
}

export function getLiveConcepts() {
  return CONCEPTS.filter((c) => c.status === "live");
}

export function getConceptById(id) {
  return CONCEPTS.find((c) => c.id === id) || null;
}
